###
# This is the place to override the opsworks_www_redirect cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "opsworks_www_redirect/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
##
